package es.rtur.pruebas.recipes.application.usecase;

import es.rtur.pruebas.recipes.application.dto.RecetaDTO;
import es.rtur.pruebas.recipes.domain.entity.Receta;
import es.rtur.pruebas.recipes.domain.repository.RecetaRepository;
import es.rtur.pruebas.recipes.domain.valueobject.RecetaId;
import es.rtur.pruebas.recipes.domain.valueobject.UsuarioId;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.validation.Valid;

/**
 * Use Case for creating a new recipe (RF-02).
 * RN-01: Only logged-in users can create recipes.
 */
@ApplicationScoped
public class CreateRecetaUseCase {

    private final RecetaRepository recetaRepository;

    @Inject
    public CreateRecetaUseCase(RecetaRepository recetaRepository) {
        this.recetaRepository = recetaRepository;
    }

    /**
     * Creates a new recipe.
     * @param dto Recipe data
     * @param idAutor ID of the user creating the recipe (from authentication context)
     * @return RecetaDTO with the created recipe data
     */
    public RecetaDTO execute(@Valid RecetaDTO dto, Integer idAutor) {
        if (idAutor == null) {
            throw new IllegalArgumentException("User must be authenticated to create a recipe");
        }

        // Create domain entity
        Receta receta = new Receta(
                null, // ID will be generated by database
                dto.getNombre(),
                dto.getTiempo(),
                dto.getComensales(),
                dto.getDificultad(),
                dto.getPreparacion(),
                dto.getCategoria(),
                UsuarioId.of(idAutor)
        );

        Receta savedReceta = recetaRepository.save(receta);

        return mapToDTO(savedReceta);
    }

    private RecetaDTO mapToDTO(Receta receta) {
        return RecetaDTO.builder()
                .id(receta.getId() != null ? receta.getId().getValue() : null)
                .nombre(receta.getNombre())
                .tiempo(receta.getTiempo())
                .comensales(receta.getComensales())
                .dificultad(receta.getDificultad())
                .preparacion(receta.getPreparacion())
                .categoria(receta.getCategoria())
                .idAutor(receta.getIdAutor().getValue())
                .fCreacion(receta.getFCreacion())
                .fModificacion(receta.getFModificacion())
                .build();
    }
}
