package es.rtur.pruebas.recipes.application.usecase;

import es.rtur.pruebas.recipes.application.dto.IngredienteDTO;
import es.rtur.pruebas.recipes.domain.entity.Ingrediente;
import es.rtur.pruebas.recipes.domain.repository.IngredienteRepository;
import es.rtur.pruebas.recipes.domain.valueobject.IngredienteId;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.validation.Valid;

/**
 * Use Case for creating an ingrediente (RF-06 - Admin only).
 */
@ApplicationScoped
public class CreateIngredienteUseCase {

    private final IngredienteRepository ingredienteRepository;

    @Inject
    public CreateIngredienteUseCase(IngredienteRepository ingredienteRepository) {
        this.ingredienteRepository = ingredienteRepository;
    }

    /**
     * Creates a new ingrediente.
     * @param dto Ingrediente data
     * @param isAdmin Whether the user is an admin
     * @return IngredienteDTO with the created ingrediente data
     */
    public IngredienteDTO execute(@Valid IngredienteDTO dto, boolean isAdmin) {
        if (!isAdmin) {
            throw new SecurityException("Only administrators can create ingredients");
        }

        Ingrediente ingrediente = new Ingrediente(
                null, // ID will be generated by database
                dto.getNombre(),
                dto.getTipo()
        );

        Ingrediente savedIngrediente = ingredienteRepository.save(ingrediente);

        return mapToDTO(savedIngrediente);
    }

    private IngredienteDTO mapToDTO(Ingrediente ingrediente) {
        return new IngredienteDTO(
                ingrediente.getId() != null ? ingrediente.getId().getValue() : null,
                ingrediente.getNombre(),
                ingrediente.getTipo(),
                ingrediente.getFCreacion(),
                ingrediente.getFModificacion()
        );
    }
}
