package es.rtur.pruebas.recipes.application.usecase;

import es.rtur.pruebas.recipes.application.dto.UtensilioDTO;
import es.rtur.pruebas.recipes.domain.entity.Utensilio;
import es.rtur.pruebas.recipes.domain.repository.UtensilioRepository;
import es.rtur.pruebas.recipes.domain.valueobject.UtensilioId;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.validation.Valid;

/**
 * Use Case for creating a utensilio (RF-06 - Admin only).
 */
@ApplicationScoped
public class CreateUtensilioUseCase {

    private final UtensilioRepository utensilioRepository;

    @Inject
    public CreateUtensilioUseCase(UtensilioRepository utensilioRepository) {
        this.utensilioRepository = utensilioRepository;
    }

    /**
     * Creates a new utensilio.
     * @param dto Utensilio data
     * @param isAdmin Whether the user is an admin
     * @return UtensilioDTO with the created utensilio data
     */
    public UtensilioDTO execute(@Valid UtensilioDTO dto, boolean isAdmin) {
        if (!isAdmin) {
            throw new SecurityException("Only administrators can create utensils");
        }

        Utensilio utensilio = new Utensilio(
                null, // ID will be generated by database
                dto.getNombre(),
                dto.getTipo()
        );

        Utensilio savedUtensilio = utensilioRepository.save(utensilio);

        return mapToDTO(savedUtensilio);
    }

    private UtensilioDTO mapToDTO(Utensilio utensilio) {
        return new UtensilioDTO(
                utensilio.getId() != null ? utensilio.getId().getValue() : null,
                utensilio.getNombre(),
                utensilio.getTipo(),
                utensilio.getFCreacion(),
                utensilio.getFModificacion()
        );
    }
}
