package es.rtur.pruebas.recipes.application.usecase;

import es.rtur.pruebas.recipes.application.dto.ValoracionDTO;
import es.rtur.pruebas.recipes.domain.entity.Valoracion;
import es.rtur.pruebas.recipes.domain.repository.ValoracionRepository;
import es.rtur.pruebas.recipes.domain.valueobject.RecetaId;
import es.rtur.pruebas.recipes.domain.valueobject.UsuarioId;
import es.rtur.pruebas.recipes.domain.valueobject.ValoracionId;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.validation.Valid;

import java.util.Optional;

/**
 * Use Case for creating/updating a valoracion (like/dislike) on a recipe (RF-04).
 * RN-04: A user can only give one like/dislike per recipe.
 */
@ApplicationScoped
public class CreateValoracionUseCase {

    private final ValoracionRepository valoracionRepository;

    @Inject
    public CreateValoracionUseCase(ValoracionRepository valoracionRepository) {
        this.valoracionRepository = valoracionRepository;
    }

    /**
     * Creates or updates a valoracion on a recipe.
     * RN-04: If user already has a valoracion, it will be updated.
     * @param dto Valoracion data
     * @param idUsuario ID of the user creating the valoracion
     * @return ValoracionDTO with the created/updated valoracion data
     */
    public ValoracionDTO execute(@Valid ValoracionDTO dto, Integer idUsuario) {
        if (idUsuario == null) {
            throw new IllegalArgumentException("User must be authenticated to rate a recipe");
        }

        RecetaId recetaId = RecetaId.of(dto.getIdReceta());
        UsuarioId usuarioId = UsuarioId.of(idUsuario);

        // Check if user already has a valoracion for this recipe (RN-04)
        Optional<Valoracion> existingValoracion = valoracionRepository.findByRecetaAndUsuario(recetaId, usuarioId);

        Valoracion valoracion;
        if (existingValoracion.isPresent()) {
            // Update existing valoracion
            valoracion = existingValoracion.get();
            if (!valoracion.isActive()) {
                // Reactivate if it was deleted
                valoracion = new Valoracion(
                        valoracion.getId(),
                        recetaId,
                        usuarioId,
                        dto.getTipo(),
                        valoracion.getFCreacion(),
                        null // Clear elimination date
                );
            } else {
                // Change the type if different
                valoracion.changeTipo(dto.getTipo());
            }
        } else {
            // Create new valoracion
            valoracion = new Valoracion(
                    null, // ID will be generated by database
                    recetaId,
                    usuarioId,
                    dto.getTipo()
            );
        }

        Valoracion savedValoracion = valoracionRepository.save(valoracion);

        return mapToDTO(savedValoracion);
    }

    private ValoracionDTO mapToDTO(Valoracion valoracion) {
        return ValoracionDTO.builder()
                .id(valoracion.getId() != null ? valoracion.getId().getValue() : null)
                .idReceta(valoracion.getIdReceta().getValue())
                .idUsuario(valoracion.getIdUsuario().getValue())
                .tipo(valoracion.getTipo())
                .fCreacion(valoracion.getFCreacion())
                .fEliminacion(valoracion.getFEliminacion())
                .build();
    }
}
