package es.rtur.pruebas.recipes.application.usecase;

import es.rtur.pruebas.recipes.application.dto.ComentarioDTO;
import es.rtur.pruebas.recipes.domain.entity.Comentario;
import es.rtur.pruebas.recipes.domain.repository.ComentarioRepository;
import es.rtur.pruebas.recipes.domain.valueobject.ComentarioId;
import es.rtur.pruebas.recipes.domain.valueobject.RecetaId;
import es.rtur.pruebas.recipes.domain.valueobject.UsuarioId;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.validation.Valid;

/**
 * Use Case for creating a comment on a recipe (RF-03).
 * RN-08: Comments can only be created by logged-in users.
 */
@ApplicationScoped
public class CreateComentarioUseCase {

    private final ComentarioRepository comentarioRepository;

    @Inject
    public CreateComentarioUseCase(ComentarioRepository comentarioRepository) {
        this.comentarioRepository = comentarioRepository;
    }

    /**
     * Creates a new comment on a recipe.
     * @param dto Comment data
     * @param idAutor ID of the user creating the comment
     * @return ComentarioDTO with the created comment data
     */
    public ComentarioDTO execute(@Valid ComentarioDTO dto, Integer idAutor) {
        if (idAutor == null) {
            throw new IllegalArgumentException("User must be authenticated to create a comment");
        }

        // Create domain entity
        Comentario comentario = new Comentario(
                null, // ID will be generated by database
                RecetaId.of(dto.getIdReceta()),
                UsuarioId.of(idAutor),
                dto.getContenido()
        );

        Comentario savedComentario = comentarioRepository.save(comentario);

        return mapToDTO(savedComentario);
    }

    private ComentarioDTO mapToDTO(Comentario comentario) {
        return new ComentarioDTO(
                comentario.getId() != null ? comentario.getId().getValue() : null,
                comentario.getIdReceta().getValue(),
                comentario.getIdAutor().getValue(),
                comentario.getContenido(),
                comentario.getEstado(),
                comentario.getFCreacion(),
                comentario.getFModificacion()
        );
    }
}
