package es.rtur.pruebas.recipes.application.usecase;

import es.rtur.pruebas.recipes.application.dto.UsuarioDTO;
import es.rtur.pruebas.recipes.domain.entity.Usuario;
import es.rtur.pruebas.recipes.domain.repository.UsuarioRepository;
import es.rtur.pruebas.recipes.domain.valueobject.UsuarioId;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.validation.Valid;

/**
 * Use Case for user registration (RF-01).
 * Handles user registration ensuring email uniqueness.
 */
@ApplicationScoped
public class RegisterUserUseCase {

    private final UsuarioRepository usuarioRepository;

    @Inject
    public RegisterUserUseCase(UsuarioRepository usuarioRepository) {
        this.usuarioRepository = usuarioRepository;
    }

    /**
     * Registers a new user.
     * @param dto User registration data
     * @return UsuarioDTO with the created user data
     * @throws IllegalArgumentException if email already exists
     */
    public UsuarioDTO execute(@Valid UsuarioDTO dto) {
        // Check if email already exists
        if (usuarioRepository.existsByEmail(dto.getEmail())) {
            throw new IllegalArgumentException("Email already exists: " + dto.getEmail());
        }

        // TODO: Hash the password before storing (implement password hashing)
        // For now, storing as-is (NOT PRODUCTION READY)
        String hashedPassword = dto.getClaveAcceso(); // Should be hashed

        // Create domain entity (ID will be generated by database)
        // Note: For auto-generated IDs, we'll use a temporary ID and let the repository handle it
        Usuario usuario = new Usuario(
                null, // ID will be set by repository after persistence
                dto.getNombre(),
                hashedPassword,
                dto.getEmail(),
                false // New users are not admins by default
        );

        Usuario savedUsuario = usuarioRepository.save(usuario);

        return mapToDTO(savedUsuario);
    }

    private UsuarioDTO mapToDTO(Usuario usuario) {
        return new UsuarioDTO(
                usuario.getId() != null ? usuario.getId().getValue() : null,
                usuario.getNombre(),
                usuario.getEmail(),
                usuario.getEsAdmin(),
                usuario.getEstado(),
                usuario.getFCreacion(),
                usuario.getFModificacion()
        );
    }
}
